### ISSUE TITLE
I can't upgrade towers 

### ISSUE THREAD

**Issue by HoriexMizuki** [doombubbles/paths-plus-plus#2]
when i try to upgrade a tower it doesn't and it shows this issue in mod meneger
![image](https://github.com/doombubbles/paths-plus-plus/assets/147771781/f1cdf70e-b176-4153-8f9a-461b80d0d810)

**Comment by PrimalTNB** [comment]
It does the same thing to me, I don't know what to do

**Comment by doombubbles** [comment]
Try the newest update https://github.com/doombubbles/paths-plus-plus/releases/tag/1.1.0

**Comment by HoriexMizuki** [comment]
thx it's working
