### ISSUE TITLE
No 4th path appears

### ISSUE THREAD

**Issue by DaleG28** [doombubbles/paths-plus-plus#6]
the title says it all its active no error in the mod menu its enabled went into sandbox no 4th upgrade path went into normal game on easy still no 4th path tried the hotkeys but nope nothing happened my btd 6 is on v45

**Comment by DaleG28** [comment]
even with the latest update theres still no path so unless its an ingame setting i havent clicked or something i dont know what could be wrong everythings now up to date as the other 2 mods now work fine but the weird thing is theres no error message or anything to my knowledge this adds a 4th upgrade path do i need it set to paragon or paths plus plus i have it on the default option which is paths++

**Comment by doombubbles** [comment]
Can you send a .../BloonsTD6/MelonLoader/Latest.log to share more details about your game environment and what mods you're using? Also just to clarify, this mod itself does not add any additional 4th paths for towers itself, it's just a resource that other mods make use of to add new paths

**Comment by DaleG28** [comment]
Oh fair enough on the readme it made it look like it incorporated all the mods or as there's 4 on the readme so we're they just mods what used this mods resources etc sorry new to modding Bloons so I know a little as I have installed mods for other gamesOn 10 Oct 2024 17:27, James Gale ***@***.***> wrote:
Can you send a .../BloonsTD6/MelonLoader/Latest.log to share more details about your game environment and what mods you're using? Also just to clarify, this mod itself does not add any additional 4th paths for towers itself, it's just a resource that other mods make use of to add new paths

**Comment by DaleG28** [comment]
i must of not understood this mod properly sorry for being a noob lmao it probably is working not an excuse as such but i was tired when i first read this mod lmao thank you all  to your hard work and commitment
